const FAMILIES = [
  {id:'effect',name:'Efecto del ataque',color:'#825cff'},
  {id:'access',name:'Conocimiento y objetivo',color:'#ff641c'},
  {id:'pipeline',name:'Pipeline y alcance',color:'#ff2e93'},
  {id:'vision',name:'Visión y biometría',color:'#9a6cff'},
  {id:'sensors',name:'Sensores y vigilancia',color:'#ff7a32'},
  {id:'cross',name:'Cruces metodológicos',color:'#f43ba8'},
  {id:'politics',name:'Política y gobernanza',color:'#72e4d1'}
];
const LEVELS = [
  {id:1,name:'Dominio'},
  {id:2,name:'Eje de clasificación'},
  {id:3,name:'Concepto / tecnología'},
  {id:4,name:'Método / familia de ataque'},
  {id:5,name:'Artefacto / implementación / recurso'}
];

const N = (id,label,family,intro,tags=[],sources=[]) => ({id,label,family,intro,tags,sources});
const nodes = [
  N('atlas','Jardín adversarial','cross','Punto de entrada a una taxonomía relacional: cada técnica puede leerse por efecto, acceso, momento, soporte y sistema.',['mapa','taxonomía']),
  N('vanishing','Vanishing','effect','Suprime detecciones reales: el modelo deja de ver objetos presentes. En TOG minimiza la confianza de objeto.',['TOG','L_obj','supresión'],[['Paper TOG','https://arxiv.org/abs/2004.04320'],['Repositorio TOG','https://github.com/git-disl/TOG']]),
  N('fabrication','Fabrication','effect','Fabrica falsos positivos en regiones vacías y puede saturar la salida del detector.',['TOG','falsos positivos'],[['Paper TOG','https://arxiv.org/abs/2004.04320']]),
  N('mislabeling','Mislabeling','effect','Conserva una detección, pero busca que el detector asigne una clase incorrecta.',['TOG','clasificación','targeted'],[['Paper TOG','https://arxiv.org/abs/2004.04320']]),
  N('untargeted','Untargeted','effect','Busca provocar un error sin fijar de antemano una salida adversarial concreta.',['FGSM','PGD','C&W'],[['Carlini & Wagner','https://arxiv.org/abs/1608.04644']]),
  N('whitebox','White-box','access','Supuesto en el que el atacante dispone de información interna suficiente para calcular gradientes exactos del modelo objetivo.',['acceso interno','gradientes'],[['Papernot et al. 2017','https://arxiv.org/abs/1602.02697']]),
  N('graybox','Gray-box','access','Etiqueta de uso variable en la literatura: aquí indica conocimiento o acceso parcial al modelo, situado entre los supuestos white-box y black-box.',['acceso parcial','terminología variable']),
  N('blackbox','Black-box','access','Opera mediante entradas y salidas; puede usar consultas, transferencia o modelos sustitutos.',['query access','transferencia'],[['Papernot et al. 2017','https://arxiv.org/abs/1602.02697']]),
  N('targeted','Targeted','access','Persigue una salida adversarial previamente especificada, por ejemplo una clase objetivo.',['objetivo específico'],[['Carlini & Wagner','https://arxiv.org/abs/1608.04644']]),
  N('evasion','Evasion','pipeline','Manipula la entrada durante la inferencia para provocar un fallo en un modelo ya entrenado.',['inferencia'],[['SoK: Security and Privacy in Machine Learning','https://arxiv.org/abs/1611.03814']]),
  N('poisoning','Poisoning','pipeline','Introduce influencia maliciosa en los datos o el proceso de entrenamiento para alterar el modelo resultante.',['entrenamiento'],[['SoK: Security and Privacy in Machine Learning','https://arxiv.org/abs/1611.03814']]),
  N('extraction','Extraction','pipeline','Busca aproximar funcionalidad, decisiones o parámetros de un modelo mediante consultas a su interfaz.',['API','consultas'],[['Model Extraction Attacks','https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/tramer']]),
  N('norms','Normas L₀ · L₂ · L∞','pipeline','Tres maneras de acotar una perturbación: cantidad de píxeles, magnitud euclidiana o cambio máximo por píxel.',['L0','L2','L∞'],[['Carlini & Wagner','https://arxiv.org/abs/1608.04644']]),
  N('physical','Realizable físicamente','cross','Perturbación diseñada y evaluada para conservar efecto bajo transformaciones del mundo físico, como impresión, iluminación, distancia, ángulo o captura. No implica eficacia garantizada fuera de las condiciones probadas.',['mundo físico','robustez'],[['Synthesizing Robust Adversarial Examples','https://arxiv.org/abs/1707.07397']]),
  N('eot','EOT','cross','Expectation over Transformation optimiza sobre una distribución de transformaciones para obtener robustez física.',['rotación','luz','distancia'],[['Athalye et al.','https://arxiv.org/abs/1707.07397']]),
  N('universal','Universal','pipeline','Una misma perturbación se diseña para afectar múltiples entradas de una distribución, en lugar de optimizarse para una sola muestra.',['reutilizable'],[['Universal Adversarial Perturbations','https://arxiv.org/abs/1610.08401']]),
  N('instance','Per-instance','pipeline','Cada muestra requiere una perturbación optimizada específicamente para ella.',['optimización individual']),
  N('dual','Dual-use','politics','Categoría analítica de este jardín: una técnica puede investigarse para evaluar robustez o proteger privacidad, pero también utilizarse para evasión. Su valoración depende del contexto, propósito y marco jurídico.',['categoría analítica','ética','contexto']),
  N('patch','Adversarial Patch','cross','Familia de ataques que concentra la perturbación en una región. Puede ser digital, física, universal, vestible, naturalista o colocarse sobre el sensor.',['patch','físico','universal'],[['Brown et al.','https://arxiv.org/abs/1712.09665']]),
  N('yolo','Detección de objetos','vision','Área que localiza y clasifica objetos mediante arquitecturas de una etapa, dos etapas, anchor-free, transformers y vocabulario abierto. Estos modelos funcionan como objetivos o bancos de prueba para ataques adversariales.',['detección','modelos objetivo','bounding boxes']),
  N('person_det','Detección de personas','vision','Tarea o clase objetivo, no una arquitectura única. YOLO, SSD, Faster R-CNN, DETR y otros detectores generales pueden localizar personas si fueron entrenados con esa categoría; también existen modelos especializados.',['persona','pedestrian','clase objetivo'],[['COCO: clase person','https://cocodataset.org/#explore']]),
  N('onestage','Una etapa','vision','Familia que predice clases y cajas en una sola pasada densa; incluye YOLO, SSD, RetinaNet y EfficientDet.',['one-stage','detección densa']),
  N('twostage','Dos etapas','vision','Familia que primero genera propuestas de región y después las clasifica o refina; Faster R-CNN y Mask R-CNN son ejemplos centrales.',['region proposals','dos etapas']),
  N('anchorfree','Anchor-free','vision','Familia que evita cajas ancla predefinidas y formula la detección mediante puntos, centros o distancias a los bordes.',['puntos','centros','sin anchors']),
  N('transformer_det','Transformers de detección','vision','Familia iniciada por DETR que trata la detección como predicción de conjuntos mediante atención y asignación bipartita.',['attention','set prediction','transformers']),
  N('openvocab','Vocabulario abierto','vision','Grounding DINO y YOLO-World permiten detección condicionada por lenguaje; YOLOE admite prompts textuales y visuales, además de un modo sin prompt.',['texto','prompts','open vocabulary'],[['Grounding DINO','https://arxiv.org/abs/2303.05499'],['YOLO-World','https://arxiv.org/abs/2401.17270'],['YOLOE','https://arxiv.org/abs/2503.07465']]),
  N('face_det','Detección facial','vision','Rama especializada en localizar rostros, a menudo junto con landmarks. Incluye desde Viola–Jones/Haar hasta MTCNN, RetinaFace, SCRFD, BlazeFace y YuNet.',['rostro','landmarks','localización facial']),
  N('yolo_alg','YOLO','vision','Detector de una etapa que formula la detección como una regresión directa desde la imagen hacia cajas y probabilidades de clase. “YOLO” designa una familia con numerosas versiones posteriores.',['one-stage','tiempo real'],[['YOLO v1','https://arxiv.org/abs/1506.02640']]),
  N('ssd','SSD','vision','Single Shot MultiBox Detector predice categorías y offsets de cajas desde mapas de características de varias escalas en una sola pasada.',['one-stage','multiescala'],[['SSD','https://arxiv.org/abs/1512.02325']]),
  N('retinanet','RetinaNet','vision','Detector denso de una etapa que introdujo focal loss para reducir el efecto del desequilibrio entre fondo y objetos.',['one-stage','focal loss'],[['Focal Loss / RetinaNet','https://arxiv.org/abs/1708.02002']]),
  N('efficientdet','EfficientDet','vision','Familia eficiente que combina EfficientNet, una red BiFPN y escalado compuesto de resolución, profundidad y ancho.',['one-stage','BiFPN','eficiencia'],[['EfficientDet','https://arxiv.org/abs/1911.09070']]),
  N('fasterrcnn','Faster R-CNN','vision','Detector de dos etapas que integra una Region Proposal Network para compartir características con la red de detección.',['dos etapas','RPN'],[['Faster R-CNN','https://arxiv.org/abs/1506.01497']]),
  N('maskrcnn','Mask R-CNN','vision','Extiende Faster R-CNN con una rama paralela que predice una máscara para cada instancia detectada.',['dos etapas','segmentación de instancias'],[['Mask R-CNN','https://arxiv.org/abs/1703.06870']]),
  N('fcos','FCOS','vision','Detector anchor-free por píxel que predice clase, distancias a los bordes de la caja y centralidad.',['anchor-free','centerness'],[['FCOS','https://arxiv.org/abs/1904.01355']]),
  N('centernet','CenterNet','vision','Representa cada objeto mediante el punto central de su caja y estima sus demás propiedades desde ese punto clave.',['anchor-free','keypoints'],[['Objects as Points','https://arxiv.org/abs/1904.07850']]),
  N('detr','DETR','vision','Detection Transformer elimina componentes diseñados a mano como anchors y supresión no máxima mediante predicción de conjuntos.',['transformer','set prediction'],[['DETR','https://arxiv.org/abs/2005.12872']]),
  N('deformable_detr','Deformable DETR','vision','Introduce atención deformable sobre pocos puntos de referencia, mejorando convergencia y detección de objetos pequeños frente a DETR.',['transformer','deformable attention'],[['Deformable DETR','https://arxiv.org/abs/2010.04159']]),
  N('dino_det','DINO','vision','Detector basado en DETR que mejora el entrenamiento con anchors dinámicos, denoising contrastivo y refinamiento de cajas. No es el modelo auto-supervisado homónimo.',['transformer','denoising','DETR'],[['DINO detector','https://arxiv.org/abs/2203.03605']]),
  N('rtdetr','RT-DETR','vision','Detector transformer diseñado para tiempo real, con codificador híbrido eficiente y selección de consultas consciente de la incertidumbre.',['transformer','tiempo real'],[['RT-DETR','https://arxiv.org/abs/2304.08069']]),
  N('groundingdino','Grounding DINO','vision','Detector de conjunto abierto que localiza objetos a partir de pares imagen–texto y expresiones libres.',['open-set','texto','grounding'],[['Grounding DINO','https://arxiv.org/abs/2303.05499']]),
  N('yoloworld','YOLO-World','vision','Detector de vocabulario abierto que alinea representaciones visuales y lingüísticas dentro de un marco YOLO eficiente.',['open vocabulary','texto','tiempo real'],[['YOLO-World','https://arxiv.org/abs/2401.17270']]),
  N('yoloe_alg','YOLOE','vision','Modelo de detección y segmentación de vocabulario abierto que admite prompts textuales, visuales y un modo sin prompt.',['open vocabulary','prompts','segmentación'],[['YOLOE','https://arxiv.org/abs/2503.07465']]),
  N('viola_jones','Viola–Jones / Haar','vision','Detector clásico en cascada que opera sobre intensidad —habitualmente imágenes visibles convertidas a escala de grises— y combina características tipo Haar, imagen integral, AdaBoost y rechazo temprano.',['rostro','Haar-like','cascada','RGB/grises'],[['Viola–Jones CVPR 2001','https://doi.org/10.1109/CVPR.2001.990517'],['Evasión mediante accesorios faciales','https://users.cs.northwestern.edu/~srutib/papers/face-rec-ccs16.pdf']]),
  N('mtcnn','MTCNN','vision','Cascada de tres redes que realiza conjuntamente detección facial y alineación mediante landmarks. Se ha evaluado frente a atributos impresos colocados sobre mascarilla o rostro en captura física RGB.',['rostro','cascada','landmarks','RGB'],[['MTCNN','https://arxiv.org/abs/1604.02878'],['Ataque físico a MTCNN','https://arxiv.org/abs/1910.06261']]),
  N('retinaface_alg','RetinaFace','vision','Detector facial de una etapa que incorpora landmarks y supervisión facial adicional para localización en distintas escalas.',['rostro','landmarks','one-stage'],[['RetinaFace','https://arxiv.org/abs/1905.00641']]),
  N('scrfd','SCRFD','vision','Familia de detectores faciales eficientes que analiza la asignación de muestras y distribuye capacidad entre etapas del backbone.',['rostro','eficiencia','one-stage'],[['SCRFD','https://arxiv.org/abs/2105.04714']]),
  N('blazeface','BlazeFace','vision','Detector facial ligero optimizado para inferencia móvil en GPU y aplicaciones interactivas en cámara.',['rostro','móvil','tiempo real'],[['BlazeFace','https://arxiv.org/abs/1907.05047']]),
  N('yunet','YuNet','vision','Detector facial compacto de OpenCV Zoo orientado a ejecución eficiente y salida de caja, cinco landmarks y puntuación.',['rostro','OpenCV','landmarks'],[['YuNet en OpenCV Zoo','https://github.com/opencv/opencv_zoo/tree/main/models/face_detection_yunet']]),
  N('face_accessories','Accesorios faciales impresos','vision','Familia de intervenciones localizadas sobre el rostro o sus proximidades —por ejemplo monturas, patrones o atributos impresos—. La evidencia es específica del detector: no se debe asumir transferencia automática entre Viola–Jones, MTCNN y detectores recientes.',['físico','wearable','rostro','evidencia por modelo'],[['Accessorize to a Crime','https://users.cs.northwestern.edu/~srutib/papers/face-rec-ccs16.pdf'],['Ataque físico a MTCNN','https://arxiv.org/abs/1910.06261']]),
  N('cvdazzle','CV Dazzle','politics','Proyecto de camuflaje para visión por computadora creado por Adam Harvey en 2010. Sus primeros looks usaron maquillaje, contraste y peinado asimétrico para interrumpir rasgos esperados por Viola–Jones. El propio proyecto advierte que esos diseños históricos no deben presentarse como eficaces contra detectores CNN actuales.',['contravigilancia','maquillaje','cabello','Viola–Jones','histórico'],[['Proyecto oficial CV Dazzle','https://adam.harvey.studio/cvdazzle'],['On Computer Vision · Adam Harvey','https://adam.harvey.studio/on-computer-vision']]),
  N('makeup','Maquillaje adversarial','vision','Familia de intervenciones cosméticas o sintetizadas sobre regiones faciales. Incluye camuflaje que busca impedir la detección y métodos optimizados que buscan alterar embeddings de identidad; esos objetivos no son equivalentes.',['maquillaje','rostro','físico/digital','privacidad']),
  N('advmakeup','Adv-Makeup','vision','Método de maquillaje adversarial que sintetiza sombra de ojos en la región orbital y usa meta-learning para mejorar transferencia black-box contra reconocimiento facial. Reporta escenarios digitales y físicos.',['maquillaje','eye shadow','black-box','identidad'],[['Adv-Makeup · IJCAI 2021','https://www.ijcai.org/proceedings/2021/173'],['Paper','https://arxiv.org/abs/2105.03162']]),
  N('face_id','Identidad facial','vision','ArcFace, FaceNet y CosFace producen embeddings para comparar o reconocer identidades; no son detectores.',['embeddings','reconocimiento'],[['ArcFace','https://arxiv.org/abs/1801.07698'],['FaceNet','https://arxiv.org/abs/1503.03832']]),
  N('tracking','Tracking','vision','ByteTrack, DeepSORT y BoT-SORT siguen objetos ya detectados a través del tiempo.',['temporal','trayectorias'],[['ByteTrack','https://arxiv.org/abs/2110.06864'],['Deep SORT','https://arxiv.org/abs/1703.07402']]),
  N('audio','Audio y voz','sensors','VAD y keyword spotting detectan actividad o eventos de voz; ASR transcribe; los sistemas de reconocimiento de hablante comparan representaciones vocales.',['Whisper','ECAPA-TDNN','VAD'],[['Whisper','https://arxiv.org/abs/2212.04356'],['ECAPA-TDNN','https://arxiv.org/abs/2005.07143']]),
  N('rgb','Cámara RGB','sensors','Superficie visual habitual en CCTV, webcam y cámaras corporales. Los patrones impresos actúan en luz visible.',['CCTV','visible']),
  N('nir','RGB–NIR / nocturna','sensors','Agrupa sistemas que combinan canales visibles y NIR, o que iluminan la escena con infrarrojo cercano durante la noche. Son configuraciones distintas; un resultado obtenido en RGB no demuestra transferencia a NIR.',['infrarrojo cercano','noche']),
  N('thermal','Cámara térmica','sensors','Registra radiación infrarroja térmica y contraste de temperatura. Los ataques físicos estudiados para esta modalidad manipulan la distribución térmica, por lo que un patrón RGB no es equivalente.',['infrarrojo térmico','multiespectral'],[['Parches infrarrojos físicos','https://arxiv.org/abs/2303.13868']]),
  N('depth','Profundidad / ToF','sensors','Estima estructura 3D y distancia mediante una modalidad de profundidad. La superficie de ataque y su viabilidad dependen del principio de medición y del modelo evaluado.',['3D','ToF','RGB-D'],[['Robustez de detección 3D por cámara','https://arxiv.org/abs/2301.10766']]),
  N('lidar','LiDAR','sensors','Produce nubes de puntos 3D procesadas por detectores especializados. Debe distinguirse entre perturbaciones digitales de puntos y objetos físicamente realizables.',['nube de puntos','geometría'],[['Ejemplos físicos para detección LiDAR','https://arxiv.org/abs/2004.00543']]),
  N('alpr','ALPR / LPR','sensors','Sistema para localizar y leer matrículas. Como abstracción experimental puede separarse en captura, localización de placa y reconocimiento de caracteres, aunque los productos propietarios no necesariamente publican esa arquitectura.',['matrículas','OCR','abstracción metodológica']),
  N('flock','Flock LPR / NightVision','cross','Caso integrado de vigilancia vial propietaria: la documentación oficial describe captura de matrículas y atributos del vehículo, además de iluminación infrarroja nocturna. Como no identifica públicamente una arquitectura neuronal concreta, una evaluación académica prudente separaría captura, lectura de placa y atributos; usaría sustitutos, transformaciones físicas y medición de transferencia sin afirmar eficacia directa.',['LPR','OCR','infrarrojo','propietario','transferencia'],[['Producto LPR de Flock','https://www.flocksafety.com/products/license-plate-readers'],['FAQ oficial de Flock','https://www.flocksafety.com/faq']]),
  N('transfer','Transferencia','cross','Evalúa si un ataque creado contra modelos sustitutos conserva eficacia en un sistema objetivo desconocido.',['surrogates','black-box']),
  N('multimodal','Evaluación multimodal','cross','Categoría metodológica de este jardín para estudiar conjuntamente superficies visuales, acústicas, temporales o de sensores. No designa por sí sola un algoritmo de ataque específico.',['categoría metodológica','audio','video','sensores']),
  N('tog','TOG','effect','Framework que formaliza ataques vanishing, fabrication, mislabeling y untargeted sobre detectores de objetos.',['paper','repositorio'],[['Repositorio oficial','https://github.com/git-disl/TOG']]),
  N('dpatch','DPatch','effect','Método de parche contra detectores que admite ataques dirigidos y no dirigidos y estudia transferencia entre Faster R-CNN y YOLO.',['patch','detector'],[['Paper DPatch','https://arxiv.org/abs/1806.02299']]),
  N('pgd','PGD / FGSM','pipeline','Métodos iterativo y de un paso basados en gradiente, usados como referencias de perturbación acotada.',['gradiente','baseline'],[['FGSM','https://arxiv.org/abs/1412.6572'],['PGD','https://arxiv.org/abs/1706.06083']]),
  N('advshirt','Adversarial T-shirt','cross','Artefacto físico vestible orientado a suprimir la detección de personas bajo deformación, pose y cambios de captura.',['wearable','persona'],[['Paper Adversarial T-shirt','https://arxiv.org/abs/1910.11099']]),
  N('advhat','AdvHat','vision','Ataque físico mediante un patrón impreso colocado en un sombrero, evaluado contra un sistema de identificación facial basado en ArcFace.',['rostro','identificación','físico'],[['Paper AdvHat','https://arxiv.org/abs/1908.08705']]),
  N('rp2','RP2','cross','Robust Physical Perturbations optimiza señales adversariales para sobrevivir variaciones físicas, inicialmente sobre señales de tránsito.',['físico','EOT','señales'],[['Paper RP2','https://arxiv.org/abs/1707.08945']]),
  N('objecthider','Object Hider','effect','Método de parche para ocultar objetos frente a detectores mediante dos variantes de generación: una basada en mapas de activación y otra en consenso.',['vanishing','patch','transferencia'],[['Paper Object Hider','https://arxiv.org/abs/2010.14974'],['Repositorio','https://github.com/FenHua/DetDak']]),
  N('translucent','Translucent Patch','sensors','Parche universal translúcido situado sobre la lente: ataca la captura sin modificar directamente el objeto.',['lente','contactless','universal'],[['Paper Translucent Patch','https://arxiv.org/abs/2012.12528']]),
  N('dap','DAP dinámico','cross','Parche dinámico y naturalista para evadir detectores de personas, diseñado para transformaciones y deformaciones no rígidas.',['naturalista','persona','físico'],[['Paper DAP','https://arxiv.org/abs/2305.11618']]),
  N('badpatch','BadPatch','cross','Generación de parches físicos naturalistas mediante difusión, con evaluación sobre múltiples familias de detectores.',['difusión','naturalista','patch'],[['Paper BadPatch','https://arxiv.org/abs/2412.01440']]),
  N('surveillance','Infraestructura de vigilancia','politics','Conjunto sociotécnico de sensores, modelos, bases de datos, operadores e instituciones que permite observar, identificar o seguir personas, vehículos y eventos.',['infraestructura','vigilancia','sociotécnico'],[['AI Now 2019 Report','https://ainowinstitute.org/publications/ai-now-2019-report-2']]),
  N('privacy','Privacidad y autonomía','politics','Marco para examinar cómo la captura, identificación y trazabilidad automatizadas afectan privacidad, libertad de movimiento, asociación y expresión.',['derechos','privacidad','autonomía'],[['SoK: Anti-Facial Recognition Technology','https://arxiv.org/abs/2112.04558']]),
  N('governance','Gobernanza y rendición de cuentas','politics','Procesos para asignar responsabilidades, documentar decisiones, evaluar impactos, monitorear riesgos y permitir revisión de sistemas de IA.',['gobernanza','auditoría','responsabilidad'],[['NIST AI RMF 1.0','https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10']]),
  N('institutional','Uso institucional','politics','Analiza quién despliega un sistema, con qué finalidad, bajo qué autoridad y qué consecuencias produce para las personas observadas.',['instituciones','finalidad','autoridad']),
  N('proprietary','Infraestructura propietaria','politics','Los sistemas cerrados limitan el conocimiento público sobre arquitectura, datos y métricas; su evaluación requiere documentar incertidumbre y trabajar con evidencia observable.',['opacidad','proveedores','evidencia']),
  N('activism','Activismo antivigilancia','politics','Prácticas sociales, jurídicas, artísticas y técnicas que cuestionan o limitan tecnologías de vigilancia y reconocimiento biométrico.',['activismo','diseño','derechos'],[['AI Now 2019 Report','https://ainowinstitute.org/publications/ai-now-2019-report-2'],['ACLU: Face Recognition Surveillance','https://www.aclu.org/news/topic/stopping-face-recognition-surveillance']]),
  N('biometric_policy','Regulación biométrica','politics','Normas y políticas que establecen condiciones, evaluaciones o límites para identificación biométrica remota y otros usos de alto impacto. Su alcance depende de la jurisdicción.',['biometría','regulación','jurisdicción'],[['Reglamento europeo de IA','https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en']])
];

const DATES = {
  patch:'2017', tog:'2020', dpatch:'2018', pgd:'FGSM 2015 · PGD 2018',
  advshirt:'2019 (preprint)', advhat:'2019', rp2:'2018', objecthider:'2020',
  translucent:'2020', dap:'2023', badpatch:'2024 preprint · 2025 publicación',
  eot:'2018', universal:'2017', norms:'2017', extraction:'2016',
  flock:'Documentación vigente consultada en 2026', governance:'2023',
  biometric_policy:'UE 2024/1689 · aplicación por etapas',
  yolo_alg:'2016', ssd:'2016', retinanet:'2017', efficientdet:'2020',
  fasterrcnn:'2015', maskrcnn:'2017', fcos:'2019', centernet:'2019',
  detr:'2020', deformable_detr:'2021', dino_det:'2023', rtdetr:'2023 preprint · 2024 publicación',
  groundingdino:'2023', yoloworld:'2024', yoloe_alg:'2025',
  viola_jones:'2001', mtcnn:'2016', retinaface_alg:'2020', scrfd:'2021',
  blazeface:'2019', yunet:'vigente en OpenCV Zoo', face_accessories:'2016–2019', cvdazzle:'2010', advmakeup:'2021'
};

// Fichas comparables: describen cada detector con los mismos cinco campos.
const PROFILES = {
  yolo_alg:{scope:'Objetos generales; incluye personas si la clase está en el entrenamiento.',input:'Imagen o video, habitualmente RGB.',structure:'Detector CNN de una etapa; la familia YOLO abarca múltiples versiones.',deployment:'Orientado a tiempo real, desde edge hasta GPU.',adversarial:'TOG, DPatch, Adversarial T-shirt y otros parches han sido evaluados en versiones concretas de YOLO.'},
  ssd:{scope:'Objetos generales; puede incluir la clase persona.',input:'Imagen o video, habitualmente RGB.',structure:'Una etapa, cajas ancla y predicción multiescala.',deployment:'Variantes ligeras para móvil/edge y variantes de mayor capacidad.',adversarial:'TOG fue evaluado directamente en SSD; otros parches requieren comprobar versión y backbone.'},
  retinanet:{scope:'Objetos generales; puede incluir personas.',input:'Imagen RGB en su formulación de referencia.',structure:'Una etapa con FPN, anchors y focal loss.',deployment:'GPU o servidor; la velocidad depende del backbone.',adversarial:'Existe evaluación de parches en literatura, pero este jardín no atribuye transferencia automática desde YOLO.'},
  efficientdet:{scope:'Objetos generales; puede incluir personas.',input:'Imagen RGB en los modelos de referencia.',structure:'Una etapa con EfficientNet, BiFPN y escalado compuesto.',deployment:'Escala de variantes pequeñas para edge a variantes de servidor.',adversarial:'Sin ataque físico específico incorporado aquí; debe evaluarse por variante.'},
  fasterrcnn:{scope:'Objetos generales; incluye personas cuando el dataset las contiene.',input:'Imagen RGB; puede adaptarse a otras modalidades mediante entrenamiento.',structure:'Dos etapas: RPN seguida por clasificación y refinamiento de cajas.',deployment:'Común en evaluación y servidor; suele priorizar precisión sobre latencia.',adversarial:'DPatch y el ataque ensemble de Adversarial T-shirt fueron evaluados directamente.'},
  maskrcnn:{scope:'Objetos e instancias: produce caja, clase y máscara; puede segmentar personas.',input:'Imagen RGB en su formulación de referencia.',structure:'Faster R-CNN con una rama paralela de máscaras.',deployment:'GPU/servidor y análisis donde se requiere segmentación por instancia.',adversarial:'No se infiere automáticamente eficacia desde Faster R-CNN: la rama de máscara cambia la salida evaluada.'},
  fcos:{scope:'Objetos generales; puede incluir personas.',input:'Imagen RGB en su formulación de referencia.',structure:'Una etapa anchor-free: clase, distancias a bordes y centerness por ubicación.',deployment:'GPU; variantes según backbone y FPN.',adversarial:'Sin método físico específico documentado en esta selección.'},
  centernet:{scope:'Objetos generales; puede incluir personas.',input:'Imagen RGB.',structure:'Anchor-free: representa objetos mediante puntos centrales y estima tamaño/offset.',deployment:'Investigación y aplicaciones de visión; rendimiento dependiente del backbone.',adversarial:'Sin método físico específico documentado en esta selección.'},
  detr:{scope:'Objetos generales; puede incluir personas.',input:'Imagen RGB en el paper original.',structure:'Transformer encoder–decoder con consultas y asignación bipartita.',deployment:'Principalmente GPU; el DETR original tiene entrenamiento largo y coste alto.',adversarial:'BadPatch reporta evaluación directa sobre DETR; la relación identifica esa evidencia específica.'},
  deformable_detr:{scope:'Objetos generales, con mejora en objetos pequeños.',input:'Imagen RGB y características multiescala.',structure:'DETR con atención deformable sobre puntos de muestreo escasos.',deployment:'GPU; investigación y sistemas de detección de alta capacidad.',adversarial:'Sin ataque físico específico incorporado aquí.'},
  dino_det:{scope:'Objetos generales; puede incluir personas.',input:'Imagen RGB y características multiescala.',structure:'Detector tipo DETR con denoising contrastivo y anchors dinámicos.',deployment:'GPU/servidor; modelo de alta capacidad.',adversarial:'Sin ataque físico específico incorporado aquí; no confundir con DINO auto-supervisado.'},
  rtdetr:{scope:'Objetos generales; puede incluir personas.',input:'Imagen o video RGB.',structure:'Transformer detector con codificador híbrido y selección de consultas.',deployment:'Diseñado para inferencia en tiempo real sobre GPU.',adversarial:'BadPatch reporta evaluación directa sobre RT-DETR; otros parches requieren pruebas separadas.'},
  groundingdino:{scope:'Objetos descritos mediante texto, incluida “persona”.',input:'Imagen RGB más texto.',structure:'Fusión visión–lenguaje y detector transformer de conjunto abierto.',deployment:'GPU/servidor; útil para grounding y anotación asistida.',adversarial:'Amplía la superficie a prompts y alineación multimodal; sin parche físico específico incorporado aquí.'},
  yoloworld:{scope:'Objetos de vocabulario abierto definidos por texto.',input:'Imagen RGB más vocabulario o prompts textuales.',structure:'Marco YOLO con alineación visión–lenguaje y vocabulario offline.',deployment:'Orientado a detección abierta eficiente y tiempo real.',adversarial:'No se supone que los ataques contra YOLO de vocabulario cerrado transfieran sin evaluación.'},
  yoloe_alg:{scope:'Objetos y máscaras mediante prompts; puede localizar personas.',input:'Imagen RGB con prompts textuales, visuales o modo sin prompt.',structure:'Familia YOLO de vocabulario abierto para detección y segmentación.',deployment:'Tiempo real según variante y hardware.',adversarial:'Modelo reciente: sin ataque físico específico incorporado en esta cartografía.'},
  viola_jones:{scope:'Rostros frontales en su configuración clásica; el marco puede entrenarse para otros objetos.',input:'Intensidad visible, normalmente RGB convertido a escala de grises.',structure:'Ventana deslizante, rasgos Haar, imagen integral, AdaBoost y cascada.',deployment:'CPU y sistemas históricos de cámara en tiempo real.',adversarial:'CV Dazzle y accesorios faciales documentaron evasión del detector; esos resultados no prueban eficacia contra CNN actuales.'},
  mtcnn:{scope:'Rostros y cinco landmarks.',input:'Fotografía o video RGB.',structure:'Cascada de tres CNN: propuesta, refinamiento y salida.',deployment:'Preprocesamiento para alineación e identificación facial.',adversarial:'Ataque físico documentado con atributos impresos sobre mascarilla o rostro.'},
  retinaface_alg:{scope:'Rostros, cinco landmarks y localización facial densa.',input:'Imagen RGB.',structure:'Detector facial de una etapa y multiescala con supervisión adicional.',deployment:'GPU/servidor y pipelines biométricos.',adversarial:'Sin accesorio o parche específico incorporado aquí; no se asume transferencia desde MTCNN.'},
  scrfd:{scope:'Rostros y landmarks según implementación.',input:'Imagen RGB.',structure:'Detector facial de una etapa optimizado por asignación de muestras y cómputo.',deployment:'Variantes desde móvil/edge hasta GPU.',adversarial:'Sin ataque físico específico incorporado aquí.'},
  blazeface:{scope:'Rostros en cámara cercana y aplicaciones interactivas.',input:'Video o imagen RGB.',structure:'Detector facial ligero inspirado en SSD y optimizado para GPU móvil.',deployment:'Teléfonos y aplicaciones en tiempo real.',adversarial:'Sin ataque físico específico incorporado aquí.'},
  yunet:{scope:'Rostros, cinco landmarks y puntuación.',input:'Imagen o video RGB.',structure:'CNN facial compacta distribuida mediante OpenCV Zoo.',deployment:'CPU, móvil y aplicaciones OpenCV en tiempo real.',adversarial:'Sin ataque físico específico incorporado aquí.'}
};

// Cinco capas de lectura. Los nodos no dependen de su posición visual para expresar jerarquía.
const level1 = new Set(['atlas']);
const level3 = new Set(['vanishing','fabrication','mislabeling','untargeted','whitebox','graybox','blackbox','targeted','evasion','poisoning','extraction','norms','physical','universal','instance','dual','yolo','person_det','twostage','openvocab','face_det','face_id','tracking','audio','rgb','nir','thermal','depth','lidar','alpr','transfer','multimodal','surveillance','privacy','governance','institutional','proprietary']);
const level5 = new Set(['advshirt','advhat','rp2','objecthider','translucent','dap','badpatch','yolo_alg','ssd','retinanet','efficientdet','fasterrcnn','maskrcnn','fcos','centernet','detr','deformable_detr','dino_det','rtdetr','groundingdino','yoloworld','yoloe_alg','viola_jones','mtcnn','retinaface_alg','scrfd','blazeface','yunet','face_accessories','cvdazzle','advmakeup']);
nodes.forEach(n=>n.level=level1.has(n.id)?1:(level3.has(n.id)?3:(level5.has(n.id)?5:4)));
nodes.forEach(n=>n.date=DATES[n.id]||null);

// Los seis ejes también funcionan como nodos de segundo nivel y articulan sus familias.
FAMILIES.forEach(f=>{const axis=N(`axis_${f.id}`,f.name,f.id,`Eje de lectura que reúne los nodos de ${f.name.toLowerCase()} y conserva sus relaciones con otras capas.`,['nivel 2','eje']);axis.level=2;nodes.push(axis);});

const edgePairs = [
 ['atlas','vanishing'],['atlas','blackbox'],['atlas','evasion'],['atlas','physical'],['atlas','yolo'],['atlas','rgb'],['atlas','dual'],
 ['vanishing','yolo'],['vanishing','face_det'],['vanishing','tracking'],['vanishing','patch'],['fabrication','yolo'],['mislabeling','targeted'],['mislabeling','face_id'],['untargeted','evasion'],['untargeted','norms'],
 ['whitebox','norms'],['whitebox','eot'],['graybox','transfer'],['blackbox','transfer'],['blackbox','extraction'],['targeted','patch'],
 ['evasion','patch'],['evasion','physical'],['poisoning','dual'],['extraction','blackbox'],['norms','instance'],['norms','universal'],
 ['physical','eot'],['physical','patch'],['physical','rgb'],['eot','patch'],['eot','nir'],['eot','alpr'],['universal','patch','puede adoptar esta forma'],['universal','transfer','se evalúa mediante'],['universal','yolo','puede atacar'],['universal','tog','admite variante'],['universal','dpatch','propiedad del parche'],['universal','translucent','propiedad declarada'],['dual','flock'],
 ['patch','yolo','puede atacar'],['patch','face_det','puede atacar'],['patch','rgb','puede desplegarse en'],['patch','nir','requiere evaluación específica'],['yolo','onestage','incluye familia'],['yolo','twostage','incluye familia'],['yolo','anchorfree','incluye familia'],['yolo','transformer_det','incluye familia'],['yolo','openvocab','incluye familia'],['yolo','tracking'],['yolo','rgb'],['twostage','thermal'],
 ['onestage','yolo_alg','incluye'],['onestage','ssd','incluye'],['onestage','retinanet','incluye'],['onestage','efficientdet','incluye'],['twostage','fasterrcnn','incluye'],['twostage','maskrcnn','incluye'],['anchorfree','fcos','incluye'],['anchorfree','centernet','incluye'],['transformer_det','detr','incluye'],['transformer_det','deformable_detr','incluye'],['transformer_det','dino_det','incluye'],['transformer_det','rtdetr','incluye'],['openvocab','groundingdino','incluye'],['openvocab','yoloworld','incluye'],['openvocab','yoloe_alg','incluye'],
 ['face_det','viola_jones','incluye'],['face_det','mtcnn','incluye'],['face_det','retinaface_alg','incluye'],['face_det','scrfd','incluye'],['face_det','blazeface','incluye'],['face_det','yunet','incluye'],
 ['viola_jones','rgb','procesa intensidad visible'],['viola_jones','face_accessories','evasión evaluada en'],['viola_jones','surveillance','antecedente de uso'],['mtcnn','rgb','modalidad evaluada'],['mtcnn','face_accessories','ataque físico evaluado'],['retinaface_alg','rgb','modalidad habitual'],['scrfd','rgb','modalidad habitual'],['blazeface','rgb','diseñado para cámara móvil'],['yunet','rgb','modalidad habitual'],['face_accessories','physical','realización física'],['face_accessories','evasion','busca evasión'],['face_accessories','patch','intervención localizada afín'],
 ['cvdazzle','viola_jones','EVIDENCIA · prueba de concepto'],['cvdazzle','face_det','interrumpe detección facial'],['cvdazzle','rgb','camuflaje en luz visible'],['cvdazzle','physical','maquillaje y peinado'],['cvdazzle','evasion','busca evasión'],['cvdazzle','vanishing','busca ausencia de detección'],['cvdazzle','privacy','motivación de privacidad'],['cvdazzle','activism','práctica contravigilancia'],['cvdazzle','surveillance','cuestiona esta infraestructura'],
 ['makeup','cvdazzle','incluye camuflaje histórico'],['makeup','advmakeup','incluye método optimizado'],['makeup','face_det','puede atacar detección'],['makeup','face_id','puede atacar identidad'],['makeup','physical','puede realizarse físicamente'],['makeup','privacy','uso de protección facial'],['advmakeup','face_id','EVIDENCIA · reconocimiento facial'],['advmakeup','blackbox','evaluado en transferencia'],['advmakeup','transfer','objetivo metodológico'],['advmakeup','targeted','admite impersonación'],['advmakeup','physical','reporta escenario físico'],['advmakeup','rgb','maquillaje en imagen visible'],
 ['yolo_alg','rgb','modalidad habitual'],['ssd','rgb','modalidad habitual'],['retinanet','rgb','modalidad habitual'],['efficientdet','rgb','modalidad habitual'],['fasterrcnn','rgb','modalidad habitual'],['maskrcnn','rgb','modalidad habitual'],['fcos','rgb','modalidad habitual'],['centernet','rgb','modalidad habitual'],['detr','rgb','modalidad habitual'],['deformable_detr','rgb','modalidad habitual'],['dino_det','rgb','modalidad habitual'],['rtdetr','rgb','modalidad habitual'],['groundingdino','rgb','imagen + texto'],['yoloworld','rgb','imagen + texto'],['yoloe_alg','rgb','imagen + prompts'],['groundingdino','multimodal','condicionado por lenguaje'],['yoloworld','multimodal','alineación visión-lenguaje'],['yoloe_alg','multimodal','prompts textuales o visuales'],
 ['person_det','yolo_alg','clase person si fue entrenado'],['person_det','ssd','clase person si fue entrenado'],['person_det','retinanet','clase person si fue entrenado'],['person_det','efficientdet','clase person si fue entrenado'],['person_det','fasterrcnn','clase person si fue entrenado'],['person_det','maskrcnn','detecta y segmenta personas'],['person_det','fcos','clase person si fue entrenado'],['person_det','centernet','clase person si fue entrenado'],['person_det','detr','clase person si fue entrenado'],['person_det','deformable_detr','clase person si fue entrenado'],['person_det','dino_det','clase person si fue entrenado'],['person_det','rtdetr','clase person si fue entrenado'],['person_det','groundingdino','prompt persona'],['person_det','yoloworld','vocabulario persona'],['person_det','yoloe_alg','prompt o clase persona'],['person_det','tracking','puede alimentar seguimiento'],['person_det','surveillance','uso posible'],['person_det','advshirt','objetivo del ataque'],['person_det','dap','objetivo del ataque'],
 ['tog','yolo_alg','EVIDENCIA · YOLO'],['tog','ssd','EVIDENCIA · SSD'],['dpatch','yolo_alg','EVIDENCIA · YOLO'],['dpatch','fasterrcnn','EVIDENCIA · Faster R-CNN'],['advshirt','yolo_alg','EVIDENCIA · YOLOv2'],['advshirt','fasterrcnn','EVIDENCIA · ensemble'],['objecthider','yolo_alg','EVIDENCIA · YOLO'],['objecthider','fasterrcnn','EVIDENCIA · Faster R-CNN'],['translucent','yolo_alg','EVIDENCIA · YOLOv5'],['dap','yolo_alg','EVIDENCIA · YOLOv7 / v3-tiny'],['badpatch','yolo_alg','EVIDENCIA · YOLOv3–v12'],['badpatch','fasterrcnn','EVIDENCIA · Faster R-CNN'],['badpatch','detr','EVIDENCIA · DETR'],['badpatch','rtdetr','EVIDENCIA · RT-DETR'],
 ['face_det','face_id'],['face_det','rgb'],['face_det','nir'],['face_id','tracking'],['tracking','multimodal'],['tracking','rgb'],
 ['audio','multimodal'],['rgb','nir'],['nir','thermal'],['thermal','depth'],['depth','lidar'],['alpr','nir'],['alpr','flock'],['flock','transfer'],['flock','blackbox'],['flock','eot'],['flock','dual'],['flock','nir'],['transfer','eot'],['multimodal','dual'],
 ['tog','vanishing','produce efecto'],['tog','fabrication','produce efecto'],['tog','mislabeling','produce efecto'],['tog','untargeted','admite variante'],['dpatch','patch','pertenece a'],['dpatch','vanishing','puede producir'],['dpatch','targeted','admite variante'],['dpatch','untargeted','admite variante'],['pgd','norms','usa restricción'],['pgd','untargeted','admite variante'],['pgd','targeted','admite variante'],['advshirt','patch','artefacto físico'],['advshirt','physical','evaluado físicamente'],['advshirt','vanishing','busca producir'],['advhat','face_id','ataca'],['advhat','physical','evaluado físicamente'],['rp2','patch','antecedente físico'],['rp2','eot','robustez a transformaciones'],['objecthider','patch','pertenece a'],['objecthider','vanishing','busca producir'],['translucent','patch','artefacto sobre sensor'],['translucent','rgb','actúa sobre captura'],['dap','patch','pertenece a'],['dap','physical','evaluado físicamente'],['badpatch','patch','pertenece a'],
 ['surveillance','rgb'],['surveillance','nir'],['surveillance','face_id'],['surveillance','tracking'],['surveillance','alpr'],['privacy','surveillance'],['privacy','face_id'],['privacy','dual'],['privacy','activism'],['governance','surveillance'],['governance','proprietary'],['governance','biometric_policy'],['institutional','surveillance'],['institutional','flock'],['institutional','governance'],['proprietary','flock'],['proprietary','blackbox'],['proprietary','transfer'],['activism','patch'],['activism','dual'],['biometric_policy','face_id'],['biometric_policy','surveillance'],['biometric_policy','institutional']
];
FAMILIES.forEach(f=>{
  edgePairs.push(['atlas',`axis_${f.id}`]);
  nodes.filter(n=>n.family===f.id&&n.level===3).forEach(n=>edgePairs.push([`axis_${f.id}`,n.id]));
});

const byId = Object.fromEntries(nodes.map(n=>[n.id,n]));
const family = id => FAMILIES.find(f=>f.id===id);
const connectedEntries = id => edgePairs.filter(e=>e[0]===id||e[1]===id).map(e=>({node:byId[e[0]===id?e[1]:e[0]],type:e[2]||'relación conceptual'}));
const connections = id => connectedEntries(id).map(e=>e.node);
const canvas=document.querySelector('#graph'),ctx=canvas.getContext('2d'),shell=canvas.parentElement;
let W=0,H=0,dpr=1,hover=null,selected=null,activeFamily='all',maxLevel=5,query='',drag=false,movedDuringDrag=false,last={x:0,y:0},camera={x:0,y:0,z:1};

function seedLayout(){
  const groups={}; FAMILIES.forEach((f,i)=>{const angle=i*(Math.PI*2/FAMILIES.length)-.8;groups[f.id]={cx:Math.cos(angle)*340,cy:Math.sin(angle)*275,items:[]};});
  nodes.forEach(n=>groups[n.family].items.push(n));
  Object.values(groups).forEach(g=>g.items.forEach((n,i)=>{if(n.level===2){n.x=g.cx;n.y=g.cy;return;}const a=i/g.items.length*Math.PI*2;const radius=n.level===3?100:(n.level===4?158:210);n.x=g.cx+Math.cos(a)*(radius+14*(i%3));n.y=g.cy+Math.sin(a)*(radius*.75+11*((i+1)%3));}));
  byId.atlas.x=0;byId.atlas.y=0;
}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=shell.clientWidth;H=shell.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
const screen=n=>({x:W/2+camera.x+n.x*camera.z,y:H/2+camera.y+n.y*camera.z});
const visible=n=>n.level<=maxLevel&&(activeFamily==='all'||n.family===activeFamily||n.id==='atlas')&&(!query||(`${n.label} ${n.intro} ${n.tags.join(' ')}`).toLowerCase().includes(query));
function draw(){
  ctx.clearRect(0,0,W,H);ctx.save();
  const related=selected?new Set([selected.id,...connections(selected.id).map(n=>n.id)]):null;
  const visibleNodes=nodes.filter(visible);
  edgePairs.forEach(([a,b,type],i)=>{const A=byId[a],B=byId[b],va=visible(A),vb=visible(B);if(!va||!vb)return;const p=screen(A),q=screen(B),highlight=selected&&(a===selected.id||b===selected.id),evidence=type?.startsWith('EVIDENCIA');ctx.beginPath();ctx.moveTo(p.x,p.y);const bend=((i%5)-2)*8*camera.z;ctx.quadraticCurveTo((p.x+q.x)/2+bend,(p.y+q.y)/2-bend,q.x,q.y);ctx.setLineDash(evidence?[4,4]:[]);ctx.strokeStyle=evidence?'#f1efed':(highlight?family(selected.family).color:(A.family===B.family?family(A.family).color:'#5c526e'));ctx.globalAlpha=selected?(highlight?(evidence?1:.98):.07):(evidence?.48:.3);ctx.lineWidth=(highlight?(evidence?2.8:2.2):(evidence?1.1:.7))*Math.max(.7,camera.z);ctx.stroke();ctx.setLineDash([]);});
  ctx.globalAlpha=1;
  const geometry=new Map();
  visibleNodes.forEach(n=>{const p=screen(n),f=family(n.family),is=n===selected||n===hover,isRelated=!related||related.has(n.id),base=[0,10,7,5.2,4.1,3.2][n.level],r=base*Math.max(.75,Math.min(camera.z,1.35));geometry.set(n.id,{p,r,is,isRelated,f});ctx.globalAlpha=isRelated?1:.15;if(is||n.level<=2){ctx.beginPath();ctx.arc(p.x,p.y,r+(n.level===2?10:12),0,Math.PI*2);ctx.strokeStyle=f.color;ctx.globalAlpha=is?.75:(isRelated?.22:.07);ctx.lineWidth=is?1.7:1;ctx.stroke();}ctx.globalAlpha=isRelated?1:.15;ctx.fillStyle=n.level===2?f.color:'#19181f';ctx.strokeStyle=f.color;ctx.lineWidth=is?3:(n.level<=2?2:1.4);ctx.fillRect(p.x-r,p.y-r,r*2,r*2);ctx.strokeRect(p.x-r,p.y-r,r*2,r*2);ctx.globalAlpha=1;});

  const occupied=visibleNodes.map(n=>{const {p,r}=geometry.get(n.id);return{x:p.x-r-3,y:p.y-r-3,w:r*2+6,h:r*2+6};});
  const overlap=(a,b)=>Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));
  [...visibleNodes].sort((a,b)=>(a===selected?-1:b===selected?1:a.level-b.level)).forEach(n=>{
    const {p,r,is,isRelated,f}=geometry.get(n.id),size=[0,11,9.5,7.5,6.8,6.2][n.level],label=n.label.toUpperCase();ctx.font=`${size}px DM Mono`;const tw=ctx.measureText(label).width,pad=3;
    const candidates=[
      {x:p.x-tw/2-pad,y:p.y+r+5,w:tw+pad*2,h:size+5},
      {x:p.x-tw/2-pad,y:p.y-r-size-8,w:tw+pad*2,h:size+5},
      {x:p.x+r+7,y:p.y-size/2-2,w:tw+pad*2,h:size+5},
      {x:p.x-r-tw-pad*2-7,y:p.y-size/2-2,w:tw+pad*2,h:size+5},
      {x:p.x-tw/2-pad,y:p.y+r+18,w:tw+pad*2,h:size+5},
      {x:p.x-tw/2-pad,y:p.y-r-size-21,w:tw+pad*2,h:size+5}
    ];
    candidates.forEach(c=>{c.x=Math.max(3,Math.min(W-c.w-3,c.x));c.y=Math.max(3,Math.min(H-c.h-3,c.y));c.score=occupied.reduce((sum,o)=>sum+overlap(c,o),0);});
    const box=candidates.sort((a,b)=>a.score-b.score)[0];occupied.push(box);const tx=box.x+box.w/2,ty=box.y+box.h-3;
    if(Math.hypot(tx-p.x,ty-p.y)>r+18){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(tx,box.y+box.h/2);ctx.strokeStyle=f.color;ctx.globalAlpha=isRelated?.22:.06;ctx.lineWidth=.6;ctx.stroke();}
    ctx.textAlign='center';if(is){ctx.globalAlpha=.96;ctx.fillStyle='#f1efed';ctx.fillRect(box.x,box.y,box.w,box.h);ctx.fillStyle='#18171d';ctx.fillText(label,tx,ty);}else{ctx.globalAlpha=isRelated?(n.level<=2?.92:.68):.1;ctx.lineWidth=2.5;ctx.strokeStyle='#19181f';ctx.strokeText(label,tx,ty);ctx.fillStyle=n.level<=2?'#d5d1d8':'#aaa6b0';ctx.fillText(label,tx,ty);}ctx.globalAlpha=1;
  });
  ctx.restore();
}
function hit(x,y){return nodes.filter(visible).reverse().find(n=>{const p=screen(n);return Math.hypot(x-p.x,y-p.y)<18;});}
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag=true;movedDuringDrag=false;last=pointerPos(e);canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const p=pointerPos(e);if(drag){const dx=p.x-last.x,dy=p.y-last.y;if(Math.hypot(dx,dy)>1)movedDuringDrag=true;camera.x+=dx;camera.y+=dy;last=p;draw();return;}hover=hit(p.x,p.y)||null;canvas.style.cursor=hover?'pointer':'grab';const tip=document.querySelector('#tooltip');if(hover){tip.textContent=hover.label;tip.style.display='block';tip.style.left=`${p.x+14}px`;tip.style.top=`${p.y+12}px`;}else tip.style.display='none';draw();});
canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch')return;const p=pointerPos(e);drag=false;if(!movedDuringDrag){const n=hit(p.x,p.y);if(n)showDetail(n);}});
canvas.addEventListener('pointercancel',()=>{drag=false;movedDuringDrag=false;});
canvas.addEventListener('pointerleave',()=>{drag=false;hover=null;document.querySelector('#tooltip').style.display='none';draw();});
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pointerPos(e),old=camera.z,next=Math.max(.48,Math.min(2.2,old*Math.exp(-e.deltaY*.001)));camera.x=p.x-W/2-(p.x-W/2-camera.x)*(next/old);camera.y=p.y-H/2-(p.y-H/2-camera.y)*(next/old);camera.z=next;draw();},{passive:false});

// Respaldo táctil para navegadores móviles que reservan el gesto de arrastre.
let touchGesture=null;
const touchPoint=(t,r)=>({x:t.clientX-r.left,y:t.clientY-r.top});
const touchDistance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const touchMiddle=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
canvas.addEventListener('touchstart',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),pts=[...e.touches].map(t=>touchPoint(t,r));if(pts.length===1)touchGesture={mode:'pan',last:pts[0],moved:false};else if(pts.length>=2)touchGesture={mode:'pinch',lastMid:touchMiddle(pts[0],pts[1]),lastDist:touchDistance(pts[0],pts[1])};},{passive:false});
canvas.addEventListener('touchmove',e=>{e.preventDefault();if(!touchGesture)return;const r=canvas.getBoundingClientRect(),pts=[...e.touches].map(t=>touchPoint(t,r));if(pts.length===1&&touchGesture.mode==='pan'){const p=pts[0],dx=p.x-touchGesture.last.x,dy=p.y-touchGesture.last.y;if(Math.hypot(dx,dy)>1)touchGesture.moved=true;camera.x+=dx;camera.y+=dy;touchGesture.last=p;draw();}else if(pts.length>=2){const mid=touchMiddle(pts[0],pts[1]),dist=touchDistance(pts[0],pts[1]);if(touchGesture.mode!=='pinch')touchGesture={mode:'pinch',lastMid:mid,lastDist:dist};const old=camera.z,next=Math.max(.4,Math.min(2.4,old*(dist/touchGesture.lastDist)));camera.x+=mid.x-touchGesture.lastMid.x;camera.y+=mid.y-touchGesture.lastMid.y;camera.x=mid.x-W/2-(mid.x-W/2-camera.x)*(next/old);camera.y=mid.y-H/2-(mid.y-H/2-camera.y)*(next/old);camera.z=next;touchGesture.lastMid=mid;touchGesture.lastDist=dist;draw();}},{passive:false});
canvas.addEventListener('touchend',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),ended=touchGesture;if(e.touches.length===1){touchGesture={mode:'pan',last:touchPoint(e.touches[0],r),moved:true};}else{touchGesture=null;if(ended?.mode==='pan'&&!ended.moved&&e.changedTouches[0]){const p=touchPoint(e.changedTouches[0],r),n=hit(p.x,p.y);if(n)showDetail(n);}}},{passive:false});
canvas.addEventListener('touchcancel',()=>{touchGesture=null;},{passive:true});

function showDetail(n){
  selected=n;const f=family(n.family),entries=connectedEntries(n.id),links=entries.map(e=>e.node);
  const direct=n.sources||[],seen=new Set(direct.map(s=>s[1]));
  const relatedSources=links.flatMap(x=>(x.sources||[]).map(s=>[`${s[0]} · vía ${x.label}`,s[1]])).filter(s=>!seen.has(s[1])&&seen.add(s[1])).slice(0,4);
  const profile=PROFILES[n.id];
  const profileBlock=profile?`<div class="detail-block algorithm-profile"><h3>FICHA DEL ALGORITMO</h3><dl><div><dt>QUÉ DETECTA</dt><dd>${profile.scope}</dd></div><div><dt>ENTRADA / SENSOR</dt><dd>${profile.input}</dd></div><div><dt>ESTRUCTURA</dt><dd>${profile.structure}</dd></div><div><dt>DESPLIEGUE</dt><dd>${profile.deployment}</dd></div><div><dt>EVIDENCIA ADVERSARIAL</dt><dd>${profile.adversarial}</dd></div></dl></div>`:'';
  const sourceBlock=(direct.length||relatedSources.length)?`<div class="detail-block" style="--node-color:${f.color}">${direct.length?`<h3>FUENTES DIRECTAS</h3>${direct.map(s=>`<a class="source-link" href="${s[1]}" target="_blank" rel="noreferrer">${s[0]}</a>`).join('')}`:''}${relatedSources.length?`<h3 class="related-heading">BIBLIOGRAFÍA RELACIONADA</h3>${relatedSources.map(s=>`<a class="source-link" href="${s[1]}" target="_blank" rel="noreferrer">${s[0]}</a>`).join('')}`:''}</div>`:'';
  const hasEvidence=entries.some(e=>e.type.startsWith('EVIDENCIA'));
  document.querySelector('#detailContent').innerHTML=`<div class="node-code" style="--node-color:${f.color}">NIVEL ${String(n.level).padStart(2,'0')} — ${LEVELS[n.level-1].name.toUpperCase()}</div><h2>${n.label}</h2>${n.date?`<span class="node-date">${n.date}</span>`:''}<p class="detail-intro">${n.intro}</p>${profileBlock}<div class="detail-block"><h3>FAMILIA / ETIQUETAS</h3><div class="tags"><span class="tag">${f.name}</span>${n.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="detail-block"><h3>INTERSECCIONES / ${entries.length}</h3>${hasEvidence?'<p class="evidence-key">EVIDENCIA = combinación evaluada en la fuente del método.</p>':''}<ul class="connections">${entries.map(({node:x,type})=>`<li><button data-node="${x.id}"><span>${x.label}<small class="relation-label ${type.startsWith('EVIDENCIA')?'verified':''}">${type}</small></span><span>→</span></button></li>`).join('')}</ul></div>${sourceBlock}`;
  document.querySelector('#detailPanel').classList.add('open');document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>showDetail(byId[b.dataset.node]));draw();
}
function reset(){camera={x:0,y:0,z:Math.min(1,Math.max(.4,Math.min((W-70)/1050,(H-70)/820)))};selected=null;document.querySelector('#detailPanel').classList.remove('open');draw();}
function buildFilters(){const root=document.querySelector('#filters');const all=[{id:'all',name:'Vista completa',color:'#f1efed'},...FAMILIES];root.innerHTML=all.map((f,i)=>`<button class="filter ${i===0?'active':''}" data-family="${f.id}" style="--family:${f.color}"><span class="num">${String(i).padStart(2,'0')}</span><span class="name">${f.name}</span><span class="count">${f.id==='all'?nodes.length:nodes.filter(n=>n.family===f.id).length}</span></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeFamily=b.dataset.family;root.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));draw();});}
document.querySelector('#searchInput').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();draw();});
document.querySelector('#depthRange').addEventListener('input',e=>{maxLevel=Number(e.target.value);document.querySelector('#depthValue').value=String(maxLevel).padStart(2,'0');if(selected&&!visible(selected)){selected=null;document.querySelector('#detailPanel').classList.remove('open');}document.querySelector('#nodeCount').textContent=`${nodes.filter(visible).length} NODOS`;draw();});
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();document.querySelector('#searchInput').focus();}if(e.key==='Escape'){document.querySelector('#detailPanel').classList.remove('open');document.querySelector('#aboutModal').hidden=true;}});
document.querySelector('#resetBtn').onclick=reset;document.querySelector('.brand').onclick=e=>{e.preventDefault();reset();};document.querySelector('#closePanel').onclick=()=>{selected=null;document.querySelector('#detailPanel').classList.remove('open');draw();};
const modal=document.querySelector('#aboutModal');document.querySelector('#aboutBtn').onclick=()=>modal.hidden=false;document.querySelector('#closeAbout').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true;};
const main=document.querySelector('main'),sidebar=document.querySelector('.sidebar'),sidebarToggle=document.querySelector('#mobileInfo');
document.querySelector('#closeSidebar').onclick=()=>{main.classList.add('sidebar-collapsed');sidebar.classList.remove('open');setTimeout(resize,290);};
sidebarToggle.onclick=()=>{if(main.classList.contains('sidebar-collapsed')){main.classList.remove('sidebar-collapsed');setTimeout(resize,290);}else sidebar.classList.toggle('open');};
document.querySelector('#nodeCount').textContent=`${nodes.length} NODOS`;window.addEventListener('resize',resize);
seedLayout();buildFilters();resize();reset();
